dist: trusty
language: cpp
compiler: gcc

branches:
  only:
   - master

addons:
  apt:
    packages:
     - libx11-dev
     - libxcursor-dev
     - libxext-dev
     - libxfixes-dev
     - libxft-dev
     - libxinerama-dev
     - cmake
     - libqt4-dev
     - qtbase5-dev

script:
 - ./configure --enable-hardening --enable-small && make -j1 V=1

