dist: trusty
language: cpp
compiler: gcc

addons:
  apt:
    packages:
      - libx11-dev
      - libxcursor-dev
      - libxext-dev
      - libxfixes-dev
      - libxft-dev
      - libxinerama-dev
      - cmake
      - libqt4-dev
      - qtbase5-dev
      - libglib2.0-dev
      - libgdk-pixbuf2.0-dev
      - libpango1.0-dev
      - libcairo2-dev
      - libxml2-dev
      - libcroco3-dev

before_script:
  - wget -c http://http.debian.net/debian/pool/main/libr/librsvg/librsvg_2.40.18.orig.tar.xz
  - tar xf librsvg_2.40.18.orig.tar.xz
  - mv librsvg-2.40.18 librsvg

script:
  - ./configure --enable-hardening --enable-rsvg
  - ( make -j4 V=1 && strip --strip-all fltk-dialog )

after_success:
  - ( mkdir out && cd out && tar cfJ fltk-dialog-x86_64_linux.tar.xz ../fltk-dialog )
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh out/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
